apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: Ashok
  template:
    metadata:
      labels:
        app: Ashok
    spec:
      containers:
        - name: pavan
          image: shaikmustafa/socialmedia:db
          ports:
            - containerPort: 80
